name: Linter

on:
    pull_request:
        branches:
            - dev
    push:
        branches:
            - master
            - dev
            - action

permissions:
    contents: read

env:
    fail-fast: true

jobs:
    Linter-suite:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v3

            - name: "Install PHP and extensions"
              uses: shivammathur/setup-php@2.7.0
              with:
                  php-version: "8.1"
                  extensions: "pdo_sqlite"
                  tools: composer:v2, php-cs-fixer

            - name: "Cache Composer packages"
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install Dependencies
              run: composer install --quiet --no-ansi --no-interaction --no-progress

            - name: "Lint composer and container"
              run: |
                make composer
                make container

            - name: "Lint yaml"
              run: make yaml

            - name: "Lint twig"
              run: make twig

            - name: "PHPCS"
              run: make phpcs
